substitutions:
  name: home-assistant-voice-0942a9
  friendly_name: Office Assistant
packages:
  Nabu Casa.Home Assistant Voice PE: github://mwmdeadpool/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: vpd+rQIUGu5rwXYgpiJEgedcj09UgCkQqZRuk5WDHnw=

micro_wake_word:
  id: mww
  models:
    # CUSTOM
    - model: https://github.com/MWMDeadpool/micro-wake-word-models/raw/main/models/v2/laszlo.json
      id: laszlo
      probability_cutoff: 0.98
      sliding_window_size: 7


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password